/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-16 08:42:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import book.model.vo.Book;
import review.model.vo.Review;
import java.util.*;
import member.model.vo.*;

public final class bookInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1526448290425L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1525827172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("book.model.vo.Book");
    _jspx_imports_classes.add("review.model.vo.Review");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println(memberLoggedIn);
	
	//클라이언트가 보낸 쿠키처리(쿠키관련)
	Cookie[] cookies = request.getCookies();
	boolean saveId = false;
	String userIdSaved = "";
	
	//최초접속시 cookie는 null임.
	if(cookies != null){
	//	System.out.println("------------------------------------");
	//	System.out.println("브라우져가 전송한 쿠키목록");
	//	System.out.println("------------------------------------");
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
	//		System.out.println(key+" : "+value);
			//아이디저장 쿠키검사
			if("saveId".equals(key)){
				saveId = true;
				userIdSaved = value;
			}
		}
	//	System.out.println("------------------------------------");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gugi\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<title>Book</title>\r\n");
      out.write("<script>\r\n");
      out.write("//메뉴상단에 고정하기.(스크롤 내려도)\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar jbOffset = $( '.fixed-search1' ).offset();\r\n");
      out.write("\t$( '.fixed-search1' ).removeClass( 'jbFixed').css(\"display\",\"none\");\r\n");
      out.write("\t$( window ).scroll( function() {\r\n");
      out.write("\t\tif ( $( document ).scrollTop() > jbOffset.top ) {\r\n");
      out.write("\t\t\t$( '.fixed-search1' ).addClass( 'jbFixed' ).css(\"display\",\"inline\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t$( '.fixed-search1' ).removeClass( 'jbFixed').css(\"display\",\"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("function fn_loginValidate(){\r\n");
      out.write("\t//아이디 검사\r\n");
      out.write("\tif($(\"#userId1\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#userId1\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t//패스워드 검사\r\n");
      out.write("\tif($(\"#password1\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#password1\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar cnt = 0;\r\n");
      out.write("\t$(\"#user1\").click(function(){\r\n");
      out.write("\t\tcnt++;\r\n");
      out.write("\t\tif(cnt%2==1){\r\n");
      out.write("\t\t\t$(\"#bubble1\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$(\"#bubble1\").css(\"display\",\"none\");\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("$(function(){\r\n");
      out.write("\t   $(\"#basket1\").click(function(){      \r\n");
      out.write("\t      ");
if( memberLoggedIn != null ) {
      out.write("\r\n");
      out.write("\t         var memberNo = ");
      out.print(memberLoggedIn.getMember_no());
      out.write(";\r\n");
      out.write("\t      ");
}
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t      location.href=\"");
      out.print(request.getContextPath());
      out.write("/basket/basketServlet?memberNo=\" + memberNo;\r\n");
      out.write("\t   });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container1\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"title1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" alt=\"logo\" id=\"img-title1\"></a></div>\r\n");
      out.write("\t\t\t<!-- 검색바 -->\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/search/searchBook\" onsubmit=\"return fn_searchBook_byteCheck();\">\r\n");
      out.write("\t\t\t<div id=\"search-container1\">\r\n");
      out.write("\t\t\t<select name=\"searchType\" id =\"searchType1_1\">\r\n");
      out.write("\t\t\t\t<option value=\"all\" class=\"all-search\">통합검색</option>\r\n");
      out.write("\t\t\t\t<option value=\"title\" class=\"title-search\">책제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"writer\" class=\"writer-search\">저자명</option>\r\n");
      out.write("\t\t\t\t<option value=\"publisher\" class=\"publisher-search\">출판사명</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"searchBook\" id=\"search-book1_1\" placeholder=\"검색명을 입력하세요.\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"search1_1\" value=\"검색\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tfunction fn_searchBook_byteCheck() {\r\n");
      out.write("\t\t\tif($(\"#search-book1_1\").val().trim() == 0) {\r\n");
      out.write("\t\t\t\talert(\"검색어를 입력하세요\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- 로그인 시작 -->\r\n");
      out.write("\t\t<div class=\"login-container1\">\r\n");
      out.write("\t\t");
 if(memberLoggedIn ==null){
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" id=\"loginFrm1\" method=\"post\" onsubmit=\"return fn_loginValidate();\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"userId1\" placeholder=\"아이디\" value=\"");
      out.print(saveId?userIdSaved:"");
      out.write("\"/> </td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password1\" placeholder=\"비밀번호\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"로그인\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId1\"");
      out.print(saveId?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"saveId1\" for=\"saveId\">아이디저장</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"join1\" value=\"회원가입\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/chooseEnroll'\"/>     \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"logged-container1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logged1\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"user1\" alt=\"user.png\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/user.png\">\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<span id=\"logged-name1\">");
      out.print(memberLoggedIn.getMember_name() );
      out.write("님</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"bubble1\" style=\"position:relative; dispaly:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"mpage1\" type=\"button\" value=\"마이페이지\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myPage';\"/>\r\n");
      out.write("\t\t\t\t\t\t<!-- ?member_id= ");
      out.print(memberLoggedIn.getMember_id());
      out.write(" -->\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<input id=\"basket1\"type=\"button\" value=\"장바구니\" />\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<input id=\"log-out1\" type=\"button\" value=\"로그아웃\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 로그인 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 메인메뉴시작 -->\r\n");
      out.write("\t\t<nav class=\"fix-nav1\">\r\n");
      out.write("\t\t\t<ul class=\"main-nav1\">\r\n");
      out.write("\t           <li class=\"book-list\"><a href=\"#\">도서</a></li>\r\n");
      out.write("\t           <li id=\"jiseojae\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/recommend/RecommenListServlet\">지서재</a></li>\r\n");
      out.write("\t           <li id=\"used-book\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/oldboard/OldBoardServlet\">중고장터</a></li>\r\n");
      out.write("\t           <li id=\"notice\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t           ");
      out.write("\r\n");
      out.write("\t           ");
if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMember_id())){ 
      out.write("\r\n");
      out.write("\t           <li id=\"ad-member3\"><a href=\"#\">회원관리</a></li>\r\n");
      out.write("\t            <li id=\"ad-book3\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/book/bookListView\">도서관리</a></li>\r\n");
      out.write("\t           ");
} 
      out.write("\r\n");
      out.write("         \t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t<!-- 상단에 고정될 검색창  -->\r\n");
      out.write("\t\t<div id=\"fixed-search-container1\" class=\"fixed-search1\">\r\n");
      out.write("\t\t<img id = \"slogo1\"src=\"");
      out.print(request.getContextPath());
      out.write("/images/small-logo.png\" alt=\"logo\" height=\"40\" width=\"70\"  style=\"vertical-align: middle\">\r\n");
      out.write("\t\t\t<select name=\"searchType1\" id =\"searchType2_1\" style=\"vertical-align: middle\">\r\n");
      out.write("\t\t\t\t<option value=\"search-all1\" >통합검색</option>\r\n");
      out.write("\t\t\t\t<option value=\"title1\" >책제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"writer1\">저자명</option>\r\n");
      out.write("\t\t\t\t<option value=\"publisher1\">출판사명</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"search-book2_1\" placeholder=\"검색명을 입력하세요.\" style=\"vertical-align: middle\"/>\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"search2_1\" value=\"검색\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<section id=\"content1\">\r\n");
      out.write("    \r\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" ");

 	Book b = (Book)request.getAttribute("book");
 	List<Review> r = (List<Review>)request.getAttribute("review");
 	String str = "";
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write(".box_detail_point5{position: relative; padding-bottom: 20px; border-bottom: 1px solid #ddd;} \r\n");
      out.write(".box_detail_point5 h1.title5{display: inline; margin-right: 10px; font-size: 24px; line-height: 27px; color: #3a60df;}\r\n");
      out.write(".content_middle5{z-index: auto;}\r\n");
      out.write(".box_detail_info5{float: left; width: 200px;}\r\n");
      out.write(".box_detail_point25{border-left: 1px solid #ddd; line-height: 27px;}\r\n");
      out.write(".box_detail_point5 .back15{margin-top: 10px; color: #777; line-height: 18px; font-size: 10px}\r\n");
      out.write(".box_detail_point5 .back55{color:black;}\r\n");
      out.write(".box_detail_point5 .back65{vertical-align: baseline; margin-right: 3px;}\r\n");
      out.write(".box_detail_point5 .dc_rate{color:#5e6b9f;}\r\n");
      out.write(".box_detail_point5 .sell_price{line-height: 30px; color: #f84450;}\r\n");
      out.write(".box_detail_point5 .intext{width: 30px;}\r\n");
      out.write(".btn_blue {margin-top:10px; margin-bottom:-60px; background-image: none;background-color: #5e6b9f !important;border: 1px solid #5e6b9f;color: #fff !important;box-shadow: none;}\r\n");
      out.write(".btn_blue2 { margin-bottom:-60px; background-image: none; background-color: #7b8ed1 !important;border: 1px solid #7b8ed1;color: #fff !important;box-shadow: none;}\r\n");
      out.write(".bookinfotable5{ margin: auto;margin-top:100px;}\r\n");
      out.write(".tab_detail_content5 {margin: auto; margin-top:30px; width: 700px;height: 36px; background-color: #fff; border: 1px solid #d7d7d7; border-spacing: 0px;}\r\n");
      out.write(".book_info_text5{color: black; text-decoration:none;}\r\n");
      out.write(".tab_detail_content5_td{border: 1px solid #d7d7d7; width:120px; text-align: center;}\r\n");
      out.write(".book_info_p{margin: 1px 20px 20px 20px;}\r\n");
      out.write(".tab_detail_content5_td2{width: 150px; height: 70px;}\r\n");
      out.write(".tab_detail_content5_td3{border: 1px solid #d7d7d7; font-size: 13px;}\r\n");
      out.write(".tab_detail_content5_td4{padding: 5px 5px 5px 50px; border-bottom: 1px solid; border-top: 1px solid; text-align: left; line-height: 120%;}\r\n");
      out.write(".comment-writer5{font-size: 15px; color: navy;}\r\n");
      out.write(".comment-date5{font-size: 15px; color: tomato;}\r\n");
      out.write(".comment-content5{font-size: 15px;}\r\n");
      out.write(".book25{width: 190px; height: 250px;}\r\n");
      out.write("table.tab_detail_content5 button.btn-delete {background: red; color: white;display: none;   float: right;}\r\n");
      out.write("table.tab_detail_content5 tr:hover button.btn-delete {display: inline;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"bookinfotable5\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td rowspan=\"4\">\r\n");
      out.write("\t\t\t\t<div class=\"box_detail_info5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_detail_cover5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bookinfocover5\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"book25\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(b.getBookNo());
      out.write(".jpg\" alt=\"book_image\" onerror=\"javascript:this.src='");
      out.print(request.getContextPath());
      out.write("/images/blank.png'\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div class=\"content_middle5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_detail_point5\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"title5\"><strong>");
      out.print(b.getBookTitle() );
      out.write("</strong></h1><br /><br />\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15\">");
      out.print( b.getAuthorName() );
      out.write(" 지음 | </span> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15\">");
      out.print( b.getBookPublisher() );
      out.write(" | </span> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15\">");
      out.print( b.getIssueDate() );
      out.write(" 출간</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td >\r\n");
      out.write("\t\t\t\t<div class=\"content_middle5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_detail_point5\">\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15\"> 정가 : ");
      out.print(b.getBookPrice() );
      out.write(" 원</span>\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15 back55\">판매가 : </span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sell_price\">");
      out.print(b.getBookPrice()-(b.getBookPrice()/10) );
      out.write(" 원</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15 dc_rate\">[10%↓ ");
      out.print(b.getBookPrice()/10 );
      out.write(" 원 할인]</span>\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"content_middle5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_detail_point5 box_detail_point25\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back45\"> <br />이 상품의 지서재 </span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div class=\"content_middle5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_detail_point5\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15 back55\">배송비 : 무료</span> <br />\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15 back55\">\r\n");
      out.write("\t\t\t\t\t\t\t\t배송일정 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 2층  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t지금 주문하면\r\n");
      out.write("\t\t\t\t\t\t</span > <br />\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15 back55\">바로드림 : 인터넷으로 주문하고 매장에서 직접 수령</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<div class=\"content_middle5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box_detail_point5 back65\">\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tif($(\"#orderBtn\").click()) {\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(memberLoggedIn!= null) {
								str = request.getContextPath()+"/buy/buyServlet"; 
							} /* else {
								str = request.getContextPath()+"/member/login";
							} */
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.print(str);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"back15 back55\">주문수량 : </span>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"number\" name=\"orderCnt\" id=\"orderCnt\" value=\"1\" class=\"intext\" min=\"1\"/> <br />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"장바구니 담기\" class=\" btn_blue\" onclick=\"fn_insertBasket();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" id=\"orderBtn\" value=\"바로구매\" class=\" btn_blue2\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"bookNo\" value=\"");
      out.print(b.getBookNo());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"tab_detail_content5\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"tab_detail_content5_td\">\r\n");
      out.write("\t\t\t\t<a href=\"#book_info5\" class=\"book_info_text5\">상품정보</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"tab_detail_content5_td\">\r\n");
      out.write("\t\t\t\t<a href=\"#book_info_review\" class=\"book_info_text5\">회원리뷰</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"tab_detail_content5_td\">\r\n");
      out.write("\t\t\t\t<a href=\"#book_info_guide\" class=\"book_info_text5\">교환/반품/품절</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<table class=\"tab_detail_content5\">\r\n");
      out.write("\t\t\t<div class=\"book_info_product5\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td\" >도서번호</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" class=\"tab_detail_content5_td\">");
      out.print(b.getBookNo() );
      out.write("</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td  class=\"tab_detail_content5_td\">쪽수</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"  class=\"tab_detail_content5_td\">");
      out.print(b.getBookPage() );
      out.write(" 쪽</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" id=\"book_info5\" class=\"book_info_table_td5\">\r\n");
      out.write("\t\t\t\t\t<h3>책소개</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t이 책의 장르 <br /><br />\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(b.getCategory() );
      out.write(" <br /><br />\r\n");
      out.write("\t\t\t\t\t\t<p class=\"book_info_p\" style=\"font-size: 12px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t사랑에 빠지는 순간은 예고 없이 찾아온다! <br /><br />\r\n");
      out.write("\t\t\t\t\t\t\t남궁현 장편소설 『더 원(The One)』 제1권. 2013년 출간된 후 로맨스 독자들의 관심과 입소문으로 사랑을 받은 작품으로, 더 많은 에피소드를 추가하고 수정하여 새롭게 독자들과 만난다. 인물 관계의 밀도와 긴장감을 높이고 외전을 대폭 늘려 결말 이후의 이야기를 새롭게 만들어 냈다. 저자의 강점인 섬세하고 촘촘한 심리 묘사가 빛을 발하는 작품이다. <br /> \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t작품을 할 때마다 열애설에 휘말려 스캔들 메이커로 낙인찍힌 배우 성현. 마지막 기회로 다가온 드라마 '온리 원'의 여주인공 선우진으로 캐스팅된다. 상대역은 뛰어난 외모와 매력으로 많은 팬을 거느린 탑스타 서재유! 그는 비주얼만 훌륭한 가수출신 연기자라는 꼬리표를 떼기 위해 '온리 원'의 김재현 역에 도전한다.  <br />\r\n");
      out.write("\t\t\t\t\t\t\t진짜 선우진과 김재현처럼 서로를 알아갈수록 낯선 설렘을 경험하는 두 사람. 하지만 더 이상 스캔들의 주인공이 되고 싶지 않은 성현은 그 마음을 부정하며 재유의 눈빛을 외면한다. 그리고 그들 사이에 나타난 또 다른 서재유. 늘 그림자처럼 숨어 있던 그가 모습을 드러내고, 성현은 똑같은 얼굴의 두 사람을 보고 충격에 빠지는데…. <br />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<hr /><br />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<h3>저자소개</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t이 책의 저자 <br /><br />\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(b.getAuthorName() );
      out.write(" <br /><br />\r\n");
      out.write("\t\t\t\t\t\t<p class=\"book_info_p\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t\t저자 아담 J. 잭슨 Adam J. Jackson은 영국 사우스햄턴대학교 법학과를 졸업하고 런던에서 법무관으로 사회에 첫발을 딛은 그는 법조계에 입문한 지 3년 만에 탄탄대로였던 법무관을 그만두고 건강, 자연의학 분야를 공부, 《너싱 타임즈》 《헬스 가디언》 등에서 저명한 칼럼니스트로 활동했다. <br /><br /> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t자기 변화와 인간관계, 스트레스 극복에 관한 많은 글을 써서 세계 출판계에도 큰 반향을 일으켰으며, 변화의 동기를 유발하는 명강사로도 유명한 그는 인간 심리에 대한 분석적이고 치밀한 논리와 종합적이고 포용력 있는 동양적 사고방식을 결합한 독특한 인생론을 설파하였다. 현재 그는 런던과 토론토에서 클리닉센터를 운영하면서 영국과 미국의 대학에서 강의하고 있다. <br /><br /> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t대표적인 저서로 돈, 사랑, 행복, 건강이라는 주제를 현대의 우화 형식으로 쓴 4권(The 10 Secrets of Abundant Wealth, The 10 Secrets of Abundant Love, The 10 Secrets of Abundant Happiness, The 10 Secrets of Abundant Health)이 있다. <br /><br /> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t이번에 새롭게 출간한 이 『내가 만난 1%의 사람들』은 아담 J. 잭슨의 대표 저서(The 10 Secrets of Abundant Wealth, Love & Happiness) 3권을 한 권으로 모은 것이다. 아담 J. 잭슨의 이 책은 영국에서 처음 발행된 이후 미국, 독일, 프랑스, 이탈리아, 스페인, 일본, 중국 등 전 세계 30여 개국에서 번역되어 1천만 명 이상의 독자들로부터 열광적인 호응을 받고 있다. <br /><br /> \r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<hr /><br />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<h3>책 속으로</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<p class=\"book_info_p\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t\t포기하지 말라! <br /> \r\n");
      out.write("\t\t\t\t\t\t\t일이 잘못되어 갈 때 <br /> \r\n");
      out.write("\t\t\t\t\t\t\t걷는 길이 계속 오르막길처럼 보일 때<br /> \r\n");
      out.write("\t\t\t\t\t\t\t저금은 줄어들고 채무만 늘어날 때 <br />\r\n");
      out.write("\t\t\t\t\t\t\t그리하여 미소를 짓고 싶어도 한숨만 나올 때 <br />\r\n");
      out.write("\t\t\t\t\t\t\t걱정이 그대를 내리누를 때 <br />\r\n");
      out.write("\t\t\t\t\t\t\t필요하다면 휴식하라. 하지만 절대로 포기하지 말라!<br /> \r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t인생은 변수와 의외로 가득하니 <br />\r\n");
      out.write("\t\t\t\t\t\t\t누구나 수많은 실패를 통해서 배운다. <br />\r\n");
      out.write("\t\t\t\t\t\t\t조금만 더 버티면 성공할지도 모르니 <br />\r\n");
      out.write("\t\t\t\t\t\t\t포기하지 말라! 비록 발걸음은 늦춰질지라도 <br />\r\n");
      out.write("\t\t\t\t\t\t\t일거에 당신은 성공할 수도 있다. <br />\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t성공은 실패를 뒤집은 것이다.  <br />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<hr /><br />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<h3>출판사 서평</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<p class=\"book_info_p\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t\t30여 개국에서 번역되어 1천만 명의 독자들에게 풍요로운 삶을 안겨준 책  <br />\r\n");
      out.write("\t\t\t\t\t\t\t세계적인 심리학자 아담 J. 잭슨의 명강의를 바탕으로 쓴 삶의 비밀 시리즈  <br />\r\n");
      out.write("\t\t\t\t\t\t\t풍요로운 삶에 필요한 돈, 사랑, 행복의 비밀을 찾아 떠나는 우화  <br />\r\n");
      out.write("\t\t\t\t\t\t\t한 편의 소설을 읽듯이 만나는 실존 인물들의 이야기 <br />\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t1% 사람들만이 남몰래 간직한 비밀스러운 이야기  <br />\r\n");
      out.write("\t\t\t\t\t\t\t“조르바는 한몫 단단히 잡고 날개가 넉넉하게 커져 날아갈 날을 기다렸다. 그는 돈을 날개라고 불렀다. <br />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<hr /><br />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" id=\"book_info_review\" class=\"book_info_table_td5\">\r\n");
      out.write("\t\t\t\t\t<h3>북로그 리뷰</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"book_info_form5\" >\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/review/bookInfoReviewInsert\" style =\"text-align: center;\" name=\"boardCommentFrm5\" >\r\n");
      out.write("\t\t\t\t\t\t\t<textarea style=\"resize: none;\" name=\"reviewText\"id=\"boardCommentContent5\" cols=\"60\" rows=\"3\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"reviewWriter\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(memberLoggedIn != null ? memberLoggedIn.getMember_id() : "");
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"reviewbookNo\" value=\"");
      out.print(b.getBookNo());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"리뷰작성\" class=\" btn_blue2\" onclick=\"fn_reviewCreate()\"/>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");
 if(r != null && !r.isEmpty()){
						for(Review re : r){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"tab_detail_content5_td3 tab_detail_content5_td4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br />&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(memberLoggedIn != null && ("admin".equals(memberLoggedIn.getMember_id()) || re.getReviewWriter().equals(memberLoggedIn.getMember_id()))) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn-delete\" value=\"");
      out.print(re.getBookNo());
      out.write("\" onclick=\"fn_boardDelete(");
      out.print(re.getBookNo());
      out.write(',');
      out.print(re.getReviewNo());
      out.write(");\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<sub class=\"comment-writer5\">");
      out.print(re.getReviewWriter());
      out.write(" &nbsp;&nbsp;&nbsp;</sub> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<sub class=\"comment-date5\">");
      out.print(re.getReviewDate() );
      out.write(" <br /></sub>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<sub class=\"comment-content5\">");
      out.print(re.getReviewContent() );
      out.write("</sub>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
} 
					}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" class=\"tab_detail_content5_td3 tab_detail_content5_td4\"><h4>리뷰가 없습니다.</h4></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" id=\"book_info_guide\" class=\"book_info_table_td5\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<h3>교환/반품/품절 안내</h3> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"book_info_p\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t※ 상품 설명에 반품/교환 관련한 안내가 있는 경우 그 내용을 우선으로 합니다. (업체 사정에 따라 달라질 수 있습니다.)\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"book_info_intro_div\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td tab_detail_content5_td2\">반품/교환방법</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td3\">\r\n");
      out.write("\t\t\t\t\t<p> \r\n");
      out.write("\t\t\t\t\t[1:1상담>반품/교환/환불] 또는 고객센터 (ㅁㅇㅁㅇ-ㅇㅇㅇㅇ) <br />\r\n");
      out.write("\t\t\t\t\t※ 오픈마켓, 해외배송주문, 기프트 주문시 [1:1상담>반품/교환/환불] <br />\r\n");
      out.write("\t\t\t\t\t    또는 고객센터 (ㅇㅇㅇㅇ-ㅇㅇㅇㅇ)\t\t\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td tab_detail_content5_td2\">반품/교환가능 기간</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td3\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t변심반품의 경우 수령 후 7일 이내, <br />\r\n");
      out.write("\t\t\t\t\t\t상품의 결함 및 계약내용과 다를 경우 문제점 발견 후 30일 이내\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td tab_detail_content5_td2\">반품/교환비용</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td3\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t변심 혹은 구매착오로 인한 반품/교환은 반송료 고객 부담\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td tab_detail_content5_td2\">반품/교환 불가 사유</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td3\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>소비자의 책임 있는 사유로 상품 등이 손실 또는 훼손된 경우 <br />\r\n");
      out.write("\t\t\t\t\t\t\t(단지 확인을 위한 포장 훼손은 제외)</li>\r\n");
      out.write("\t\t\t\t\t\t<li>소비자의 사용, 포장 개봉에 의해 상품 등의 가치가 현저히 감소한 경우 <br />\r\n");
      out.write("\t\t\t\t\t\t\t예) 화장품, 식품, 가전제품(악세서리 포함) 등</li>\r\n");
      out.write("\t\t\t\t\t\t<li>복제가 가능한 상품 등의 포장을 훼손한 경우 <br />\r\n");
      out.write("\t\t\t\t\t\t\t예) 음반/DVD/비디오, 소프트웨어, 만화책, 잡지, 영상 화보집</li>\r\n");
      out.write("\t\t\t\t\t\t<li> 소비자의 요청에 따라 개별적으로 주문 제작되는 상품의 경우 ((1)해외주문도서)</li>\r\n");
      out.write("\t\t\t\t\t\t<li> 디지털 컨텐츠인 eBook, 오디오북 등을 1회 이상 다운로드를 받았을 경우</li>\r\n");
      out.write("\t\t\t\t\t\t<li>시간의 경과에 의해 재판매가 곤란한 정도로 가치가 현저히 감소한 경우</li>\r\n");
      out.write("\t\t\t\t\t\t<li>전자상거래 등에서의 소비자보호에 관한 법률이 정하는 소비자 청약철회 제한 내용에 <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t해당되는 경우</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td tab_detail_content5_td2\">상품 품절</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td3\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t공급사(출판사) 재고 사정에 의해 품절/지연될 수 있으며, 품절 시 관련 사항에 대해서는 <br />\r\n");
      out.write("\t\t\t\t\t\t이메일과 문자로 안내드리겠습니다. \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td tab_detail_content5_td2\">소비자 피해보상 환불지연에 따른 배상</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"tab_detail_content5_td3\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>상품의 불량에 의한 교환, A/S, 환불, 품질보증 및 피해보상 등에 관한 사항은 <br />\r\n");
      out.write("\t\t\t\t\t\t소비자분쟁해결 기준 (공정거래위원회 고시)에 준하여 처리됨\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t대금 환불 및 환불지연에 따른 배상금 지급 조건, 절차 등은 전자상거래 등에서의 <br />\r\n");
      out.write("\t\t\t\t\t\t소비자 보호에 관한 법률에 따라 처리함</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</table>\r\n");
      out.write("<script>\r\n");
      out.write("function fn_reviewCreate(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"[name=boardCommentFrm5]\").submit(function(e){\r\n");
      out.write("\t\t\tif(");
      out.print(memberLoggedIn == null);
      out.write("){\r\n");
      out.write("\t\t\t\tfn_loginAlert();\r\n");
      out.write("\t\t\t\t$('#boardCommentContent5').val('');\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar len = $(\"#boardCommentContent5\").val().trim().length;\r\n");
      out.write("\t\t\tif(len==0){\r\n");
      out.write("\t\t\t\t$('#boardCommentContent5').attr('placeholder','댓글을 입력해주세요');\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("function fn_loginAlert() {\r\n");
      out.write("\talert(\"로그인 후 이용하실 수 있습니다.\");\r\n");
      out.write("\t$(\"#userId\").focus();\r\n");
      out.write("}\r\n");
      out.write("function fn_boardDelete(bno, rno){\r\n");
      out.write("\tconsole.log(bno);\r\n");
      out.write("\tconsole.log(rno);\r\n");
      out.write("\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/review/BookReviewDelete?bno=\"+bno+\"&rno=\"+rno+\"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_insertBasket(){\t\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/basket/insertBasket\",\r\n");
      out.write("\t\tdata : {\r\n");
      out.write("\t\t\tmemberNo : ");
      out.print(memberLoggedIn.getMember_no());
      out.write(",\r\n");
      out.write("\t\t\tbookNo : ");
      out.print(b.getBookNo() );
      out.write(",\r\n");
      out.write("\t\t\torderCnt : $(\"#orderCnt\").val(),\r\n");
      out.write("\t\t\tstatus : \"");
      out.print(b.getBookStatus());
      out.write("\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : \"html\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar check = confirm(\"장바구니에 담겼습니다. 장바구니로 이동하시겠습니까?\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( check )\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/basket/basketServlet?memberNo=\" + ");
      out.print(memberLoggedIn.getMember_no());
      out.write(";\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write(" </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2018. <strong>영중문고</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t\t<p>주소 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 2F, 3F</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
