/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-17 05:57:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class newMemberEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1526471529744L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1525827172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println(memberLoggedIn);
	
	//클라이언트가 보낸 쿠키처리(쿠키관련)
	Cookie[] cookies = request.getCookies();
	boolean saveId = false;
	String userIdSaved = "";
	
	//최초접속시 cookie는 null임.
	if(cookies != null){
	//	System.out.println("------------------------------------");
	//	System.out.println("브라우져가 전송한 쿠키목록");
	//	System.out.println("------------------------------------");
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
	//		System.out.println(key+" : "+value);
			//아이디저장 쿠키검사
			if("saveId".equals(key)){
				saveId = true;
				userIdSaved = value;
			}
		}
	//	System.out.println("------------------------------------");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gugi\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<title>Book</title>\r\n");
      out.write("<script>\r\n");
      out.write("//메뉴상단에 고정하기.(스크롤 내려도)\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar jbOffset = $( '.fixed-search1' ).offset();\r\n");
      out.write("\t$( '.fixed-search1' ).removeClass( 'jbFixed').css(\"display\",\"none\");\r\n");
      out.write("\t$( window ).scroll( function() {\r\n");
      out.write("\t\tif ( $( document ).scrollTop() > jbOffset.top ) {\r\n");
      out.write("\t\t\t$( '.fixed-search1' ).addClass( 'jbFixed' ).css(\"display\",\"inline\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t$( '.fixed-search1' ).removeClass( 'jbFixed').css(\"display\",\"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("function fn_loginValidate(){\r\n");
      out.write("\t//아이디 검사\r\n");
      out.write("\tif($(\"#userId1\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#userId1\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t//패스워드 검사\r\n");
      out.write("\tif($(\"#password1\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#password1\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar cnt = 0;\r\n");
      out.write("\t$(\"#user1\").click(function(){\r\n");
      out.write("\t\tcnt++;\r\n");
      out.write("\t\tif(cnt%2==1){\r\n");
      out.write("\t\t\t$(\"#bubble1\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$(\"#bubble1\").css(\"display\",\"none\");\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("$(function(){\r\n");
      out.write("\t   $(\"#basket1\").click(function(){      \r\n");
      out.write("\t      ");
if( memberLoggedIn != null ) {
      out.write("\r\n");
      out.write("\t         var memberNo = ");
      out.print(memberLoggedIn.getMember_no());
      out.write(";\r\n");
      out.write("\t      ");
}
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t      location.href=\"");
      out.print(request.getContextPath());
      out.write("/basket/basketServlet?memberNo=\" + memberNo;\r\n");
      out.write("\t   });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container1\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"title1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" alt=\"logo\" id=\"img-title1\"></a></div>\r\n");
      out.write("\t\t\t<!-- 검색바 -->\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/search/searchBook\" onsubmit=\"return fn_searchBook_byteCheck();\">\r\n");
      out.write("\t\t\t<div id=\"search-container1\">\r\n");
      out.write("\t\t\t<select name=\"searchType\" id =\"searchType1_1\">\r\n");
      out.write("\t\t\t\t<option value=\"all\" class=\"all-search\">통합검색</option>\r\n");
      out.write("\t\t\t\t<option value=\"title\" class=\"title-search\">책제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"writer\" class=\"writer-search\">저자명</option>\r\n");
      out.write("\t\t\t\t<option value=\"publisher\" class=\"publisher-search\">출판사명</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"searchBook\" id=\"search-book1_1\" placeholder=\"검색명을 입력하세요.\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"search1_1\" value=\"검색\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tfunction fn_searchBook_byteCheck() {\r\n");
      out.write("\t\t\tif($(\"#search-book1_1\").val().trim() == 0) {\r\n");
      out.write("\t\t\t\talert(\"검색어를 입력하세요\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- 로그인 시작 -->\r\n");
      out.write("\t\t<div class=\"login-container1\">\r\n");
      out.write("\t\t");
 if(memberLoggedIn ==null){
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" id=\"loginFrm1\" method=\"post\" onsubmit=\"return fn_loginValidate();\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"userId1\" placeholder=\"아이디\" value=\"");
      out.print(saveId?userIdSaved:"");
      out.write("\"/> </td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password1\" placeholder=\"비밀번호\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"로그인\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId1\"");
      out.print(saveId?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"saveId1\" for=\"saveId\">아이디저장</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"join1\" value=\"회원가입\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/chooseEnroll'\"/>     \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"logged-container1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logged1\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"user1\" alt=\"user.png\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/user.png\">\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<span id=\"logged-name1\">");
      out.print(memberLoggedIn.getMember_name() );
      out.write("님</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"bubble1\" style=\"position:relative; dispaly:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"mpage1\" type=\"button\" value=\"마이페이지\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myPage';\"/>\r\n");
      out.write("\t\t\t\t\t\t<!-- ?member_id= ");
      out.print(memberLoggedIn.getMember_id());
      out.write(" -->\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<input id=\"basket1\"type=\"button\" value=\"장바구니\" />\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<input id=\"log-out1\" type=\"button\" value=\"로그아웃\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 로그인 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 메인메뉴시작 -->\r\n");
      out.write("\t\t<nav class=\"fix-nav1\">\r\n");
      out.write("\t\t\t<ul class=\"main-nav1\">\r\n");
      out.write("\t           <li class=\"book-list\"><a href=\"#\">도서</a></li>\r\n");
      out.write("\t           <li id=\"jiseojae\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/recommend/RecommenListServlet\">지서재</a></li>\r\n");
      out.write("\t           <li id=\"used-book\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/oldboard/OldBoardServlet\">중고장터</a></li>\r\n");
      out.write("\t           <li id=\"notice\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t           ");
      out.write("\r\n");
      out.write("\t           ");
if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMember_id())){ 
      out.write("\r\n");
      out.write("\t           <li id=\"ad-member3\"><a href=\"#\">회원관리</a></li>\r\n");
      out.write("\t            <li id=\"ad-book3\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/book/bookListView\">도서관리</a></li>\r\n");
      out.write("\t           ");
} 
      out.write("\r\n");
      out.write("         \t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t<!-- 상단에 고정될 검색창  -->\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/search/searchBook\" onsubmit=\"return fn_searchBook_byteCheck();\">\r\n");
      out.write("\t\t<div id=\"fixed-search-container1\" class=\"fixed-search1\">\r\n");
      out.write("\t\t<img id = \"slogo1\"src=\"");
      out.print(request.getContextPath());
      out.write("/images/small-logo.png\" alt=\"logo\" height=\"40\" width=\"70\"  style=\"vertical-align: middle\">\r\n");
      out.write("\t\t\t<select name=\"searchType1\" id =\"searchType2_1\" style=\"vertical-align: middle\">\r\n");
      out.write("\t\t\t\t<option value=\"search-all1\" >통합검색</option>\r\n");
      out.write("\t\t\t\t<option value=\"title1\" >책제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"writer1\">저자명</option>\r\n");
      out.write("\t\t\t\t<option value=\"publisher1\">출판사명</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"search-book2_1\" placeholder=\"검색명을 입력하세요.\" style=\"vertical-align: middle\"/>\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"search2_1\" value=\"검색\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<section id=\"content1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#s3 {font-size:8pt}\r\n");
      out.write("\r\n");
      out.write(".ta3{ \r\n");
      out.write("\tborder-collapse:collapse; \r\n");
      out.write("\tfont-size:9pt; \r\n");
      out.write("\tborder:1px solid black;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("}  \r\n");
      out.write(".ta3 th, .ta3 td { border:1px solid black; }\r\n");
      out.write(".ta3 td{ padding-left: 10px; }\r\n");
      out.write("\r\n");
      out.write(".h2_3 {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    padding: 2px 0 10px;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    color: #333333;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#line3{\r\n");
      out.write("\tborder :1px dashed black; \r\n");
      out.write("\tmargin-bottom: 35px;\r\n");
      out.write("}\r\n");
      out.write("#cap3{text-align: left;}\r\n");
      out.write("#essential3{\r\n");
      out.write(" color: red;\r\n");
      out.write("}\r\n");
      out.write("#title3{\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\ttext-align: right; \r\n");
      out.write("\tpadding-right: 10px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: lightgray;\r\n");
      out.write("\tbackground-color: #333333;\r\n");
      out.write("}\r\n");
      out.write("#details3{\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("// 아이디 검색창 띄우기\r\n");
      out.write("function winOpen(){\r\n");
      out.write("\twindow.open(\"idChk.html\",\"w\",\"width=300, height=100, resizable=yes\");\r\n");
      out.write("\t/* 속성에 빈칸으로 구분했으면 계속 빈칸, 콤마로 구분했으면 계속 콤마\r\n");
      out.write("\t// 1. 새창에 표시될 파일명\r\n");
      out.write("\t// 2. 창이름: 없을 때도 \"\" 따옴표는 해줘야한다.\r\n");
      out.write("\t// 이름이 없다면 팝업창이 계속 열린다. 이름이라는 것이 \r\n");
      out.write("\t// 중복으로 띄움을 방지하도록 체크하는 역할\r\n");
      out.write("\t// 3. 속성 width: 창너비, height: 창높이\r\n");
      out.write("\t\t\t   location: 주소표시줄, menubar: 메뉴표시\r\n");
      out.write("\t\t\t   resizable : 창의 크기조절여부\r\n");
      out.write("\t\t\t   scrollbars : 스크롤바 표시여부\r\n");
      out.write("\t\t\t   toolbar : 툴바표시여부\r\n");
      out.write("\t// 속성은 yes / no 로 표시\r\n");
      out.write("\t*/\r\n");
      out.write("}\r\n");
      out.write("// 대화명 검사창 띄우기 닉네임 입력되고 창 닫힘\r\n");
      out.write("function nickChk(){window.open(\"nickChk.html\",\"n\",\"width=300, height=100\")}\r\n");
      out.write("// 우편번호 검사창 띄우기 3칸이 입력되고 창 닫힘\r\n");
      out.write("function zipChk(){window.open(\"zipChkClose.html\",\"n\",\"width=300, height=100\")}\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function memChk(){ // 데이터 입력유무 확인 스크립트\r\n");
      out.write("\tvar memId = $(\"#memId3\").val().trim();\r\n");
      out.write("\tif(memId.length == 0){\r\n");
      out.write("   \t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("   \t\treturn;\r\n");
      out.write("  \t}\r\n");
      out.write("\tif(memId.length< 4){\r\n");
      out.write("\t\talert(\"아이디는 4글자 이상이여야 합니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write(" /*  if(document.frm.memPwd.value == \"\"){\r\n");
      out.write("   alert(\"비밀번호를 입력하세요\")\r\n");
      out.write("   document.frm.memPwd.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memPwdChk.value == \"\"){\r\n");
      out.write("   alert(\"비밀번호를 다시한번 입력해주세요\")\r\n");
      out.write("   document.frm.memPwdChk.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memPwd.value != frm.memPwdChk.value){\r\n");
      out.write("   alert(\"비밀번호가 다릅니다.\");\r\n");
      out.write("   document.frm.memPwd.value = \"\"; \r\n");
      out.write("   document.frm.memPwdChk.value = \"\"; \r\n");
      out.write("   document.frm.memPwd.focus(); \r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memName.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"이름이 없는건가..\") \r\n");
      out.write("   document.frm.memName.focus(); \r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memBirth01.value == \"\" || frm.memBirth02.value == \"\" || frm.memBirth03.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"생년월일을 입력하세요.\") \r\n");
      out.write("   document.frm.memBirth01.focus(); \r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memEmail.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"이메일을 입력하세요\") \r\n");
      out.write("   document.frm.memEmail.focus(); \r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  // 메일 수신은 수신동의 selected\r\n");
      out.write("  if(document.frm.memZipCode01.value == \"\" || frm.memZipCode02.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"우편번호를 입력하세요\") \r\n");
      out.write("   document.frm.memZipCode01.focus(); \r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memAddr1.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"주소를 입력하세요\")\r\n");
      out.write("   document.frm.memAddr1.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.frm.memAddr2.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"상세 주소를 입력하세요\")\r\n");
      out.write("   document.frm.memAddr2.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (document.frm.memTel01.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"전화번호를 선택하세요\")\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (document.frm.memTel02.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"전화번호를 입력하세요\")\r\n");
      out.write("   document.frm.memTel02.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (document.frm.memTel03.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"전화번호를 입력하세요\")\r\n");
      out.write("   document.frm.memTel03.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (document.frm.memMobile01.value == \"Not\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"핸드폰번호를 선택하세요\")\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (document.frm.memMobile02.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"핸드폰번호를 입력하세요\")\r\n");
      out.write("   document.frm.memMobile02.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (document.frm.memMobile03.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("   alert(\"핸드폰번호를 입력하세요\")\r\n");
      out.write("   document.frm.memMobile03.focus();\r\n");
      out.write("   return false;\r\n");
      out.write("  } */\r\n");
      out.write("  return true;\r\n");
      out.write("  /* document.frm.submit(); // 버튼으로 쓸 땐 return true; 대신 이걸 쓰고 form시작 구문에 onsubmit=\"return memChk()\" 는 불필요하여 삭제 */\r\n");
      out.write("\r\n");
      out.write(" } \r\n");
      out.write(" </script>\r\n");
      out.write("<h2 class=\"h2_3\">Join With Us</h2>\r\n");
      out.write("<hr id=\"line3\" />\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/memberEnrollEnd\" method=\"post\" name=\"frm\"  onsubmit=\"return memChk()\"> \r\n");
      out.write("\t<table class=\"ta3\">\r\n");
      out.write("\t<caption id=\"cap3\">\r\n");
      out.write("\t\t<span id = \"essential3\">*</span><span id = \"s3\"> 항목은 필수 입력항목입니다.</span>\r\n");
      out.write("\t</caption>\r\n");
      out.write(" \t<tr height=\"60\">\r\n");
      out.write(" \t\t<td id=\"title3\" >\r\n");
      out.write(" \t\t\t<span id = \"essential3\">*</span> 아&nbsp;이&nbsp;디&nbsp;\r\n");
      out.write("  \t    </td>\r\n");
      out.write("\t\t<td width=\"600\">  \r\n");
      out.write("\t  \t\t<input type=\"text\" name=\"memId\" id=\"memId3\" size=\"16\">&nbsp;&nbsp;\r\n");
      out.write("\t   \t\t<input type=\"button\" id=\"memId_chk3\" value=\"ID중복검사\" onClick=\"winOpen()\"><br>  \r\n");
      out.write("\t   \t\t<span id = \"details3\">아이디는 영소문자,숫자 조합으로 하셔야 합니다.[4자리이상 12자리이하]</span><br>\r\n");
      out.write("\t \t</td> <!-- 중복검사............ㅡ,.ㅡa -->\r\n");
      out.write(" \t</tr>\r\n");
      out.write("\r\n");
      out.write(" \t<tr height=\"50\">\r\n");
      out.write(" \t\t<td id=\"title3\">\r\n");
      out.write(" \t\t\t<span id = \"essential3\">*</span> 암&nbsp;&nbsp;&nbsp;&nbsp;호\r\n");
      out.write(" \t\t</td>\r\n");
      out.write("\t  <td>\r\n");
      out.write("\t\t  <input type=\"password\" name=\"memPwd\" id= \"memPwd3\" size=\"16\"><br>\r\n");
      out.write("\t\t  <span id = \"details3\">비밀번호는 4자리이상 12자리이하로 입력해주세요.</span>\r\n");
      out.write("\t  </td>\r\n");
      out.write("\t  <!-- 비밀번호 문자와 숫자 혼합사용 체크....? -ㅅ-a -->\r\n");
      out.write(" \t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<td id=\"title3\">\r\n");
      out.write("\t\t\t<span id = \"essential3\">*</span> 암호확인\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t    <td>\r\n");
      out.write("\t   \t\t<input type=\"password\" name=\"memPwdChk\" id=\"memPwdChk\" size=\"16\">\r\n");
      out.write("\t    </td>\r\n");
      out.write(" \t</tr> \r\n");
      out.write(" \t<tr height=\"40\">\r\n");
      out.write("  \t\t<td id=\"title3\">\r\n");
      out.write("  \t\t\t<span id = \"essential3\">*</span> 이&nbsp;&nbsp;&nbsp;&nbsp;름\r\n");
      out.write(" \t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"memName\" size=\"16\" maxlength=\"28\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t<tr height=\"40\">\r\n");
      out.write("\t\t<td id=\"title3\">\r\n");
      out.write("\t\t<span id = \"essential3\">*</span> 성&nbsp;&nbsp;&nbsp;&nbsp;별\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"M\">남자&nbsp;\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"F\">여자\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr> <!-- 주민번호 입력에 따른 남녀 성별 체크 -.-a -->\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<td id=\"title3\">생년월일\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"memBirth\" size=\"12\" maxlength=\"10\"placeholder=\"ex)19960304\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr> <!-- 주민번호 입력에 따른 생년월일 적용 체크 -.-a -->\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<td id=\"title3\">E - mail</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"email\" name=\"memEmail\" size=\"28\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<td id=\"title3\">\r\n");
      out.write("\t\t<span id = \"essential3\">*</span> 주&nbsp;&nbsp;&nbsp;&nbsp;소</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"postnum\" id=\"sample4_postcode\" placeholder=\"우편번호\"> \r\n");
      out.write("            <input type=\"button\" class=\"btn2\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("            <input type=\"text\" name=\"address1\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\" size=\"35px\"> <br /> \r\n");
      out.write("            <input type=\"text\" name=\"address2\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\" size=\"35px\">\r\n");
      out.write("            <span id=\"guide\" style=\"color: #999\"></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<td id=\"title3\"> 휴 대 폰</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"memMobile01\" size=\"1\" maxlength=\"3\">\r\n");
      out.write("\t\t\t - \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"memMobile02\" size=\"2\" maxlength=\"4\">\r\n");
      out.write("\t\t\t -\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"memMobile03\" size=\"2\" maxlength=\"4\"> \r\n");
      out.write("\t\t</td> <!-- 숫자만 입력가능?? -.-a -->\r\n");
      out.write("\t</tr>\r\n");
      out.write("<tr height=\"40\">\r\n");
      out.write("  <td id=\"title3\"> 관심 책 분야</td>\r\n");
      out.write("  <td>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter1\" value=\"20세기 한국 소설\">\r\n");
      out.write("\t  <label for=\"inter1\">20세기 한국소설</label>&nbsp;\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter2\" value=\"경제\">\r\n");
      out.write("\t  <label for=\"inter2\">경제</label>&nbsp;\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter3\" value=\"과학\">\r\n");
      out.write("\t  <label for=\"inter3\">과학</label>&nbsp;\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter4\" value=\"과학·교양\">\r\n");
      out.write("\t  <label for=\"inter4\">과학·교양</label>&nbsp;\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter5\" value=\"과학·환경\">\r\n");
      out.write("\t  <label for=\"inter5\">과학·환경</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter6\" value=\"교양\">\r\n");
      out.write("\t  <label for=\"inter6\">교양</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter7\" value=\"그림책\">\r\n");
      out.write("\t  <label for=\"inter7\">그림책</label>\r\n");
      out.write("\t  <br />\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter8\" value=\"동시·동요\">\r\n");
      out.write("\t  <label for=\"inter8\">동시·동요</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter9\" value=\"문학\">\r\n");
      out.write("\t  <label for=\"inter9\">문학</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter10\"value=\"문학비평\">\r\n");
      out.write("\t  <label for=\"inter10\">문학비평</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter11\"value=\"문학이론\">\r\n");
      out.write("\t  <label for=\"inter11\">문학이론</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter12\"value=\"산문\">\r\n");
      out.write("\t  <label for=\"inter12\">산문</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter13\"value=\"선집·전집\">\r\n");
      out.write("\t  <label for=\"inter13\">선집·전집</label>\r\n");
      out.write("\t  <br />\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter14\"value=\"선집·전집·전작\">\r\n");
      out.write("\t  <label for=\"inter14\">선집·전집·전작</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter15\"value=\"세계명작\">\r\n");
      out.write("\t  <label for=\"inter15\">세계명작</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter16\"value=\"소설집\">\r\n");
      out.write("\t  <label for=\"inter16\">소설집</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter17\"value=\"신나는 책 읽기\">\r\n");
      out.write("\t  <label for=\"inter17\">신나는 책 읽기</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter18\"value=\"안과밖\">\r\n");
      out.write("\t  <label for=\"inter18\">안과밖</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter19\"value=\"어린이 문집\">\r\n");
      out.write("\t  <label for=\"inter19\">어린이 문집</label>\r\n");
      out.write("\t  <br />\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter20\"value=\"여성\">\r\n");
      out.write("\t  <label for=\"inter20\">여성</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter21\"value=\"여성과사회\">\r\n");
      out.write("\t  <label for=\"inter21\">여성과사회</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter22\"value=\"역사\">\r\n");
      out.write("\t  <label for=\"inter22\">역사</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter23\"value=\"역사 이야기\">\r\n");
      out.write("\t  <label for=\"inter23\">역사 이야기</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter24\"value=\"옛날 이야기\">\r\n");
      out.write("\t  <label for=\"inter24\">옛날 이야기</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter25\"value=\"외국 소설\">\r\n");
      out.write("\t  <label for=\"inter26\">외국 소설</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter26\"value=\"외국 시\">\r\n");
      out.write("\t  <label for=\"inter26\">외국 시</label>\r\n");
      out.write("\t  <br />\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter27\"value=\"이 세상 첫 이야기\">\r\n");
      out.write("\t  <label for=\"inter27\">이 세상 첫 이야기</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter28\"value=\"인문\">\r\n");
      out.write("\t  <label for=\"inter28\">인문</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter29\"value=\"인물 이야기\">\r\n");
      out.write("\t  <label for=\"inter29\">인물 이야기</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter30\"value=\"인물·평전\">\r\n");
      out.write("\t  <label for=\"inter30\">인물·평전</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter31\"value=\"장편소설\">\r\n");
      out.write("\t  <label for=\"inter31\">장편소설</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter32\"value=\"정치·사회\">\r\n");
      out.write("\t  <label for=\"inter32\">정치·사회</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter33\"value=\"창비시선\">\r\n");
      out.write("\t  <label for=\"inter33\">창비시선</label>\r\n");
      out.write("\t  <br />\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter34\"value=\"창비어린이\">\r\n");
      out.write("\t  <label for=\"inter34\">창비어린이</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter35\"value=\"창작과비평\">\r\n");
      out.write("\t  <label for=\"inter35\">창작과비평</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter36\"value=\"창작동화\">\r\n");
      out.write("\t  <label for=\"inter36\">창작동화</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter37\"value=\"철학\">\r\n");
      out.write("\t  <label for=\"inter37\">철학</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter38\"value=\"환경\">\r\n");
      out.write("\t  <label for=\"inter38\">환경</label>\r\n");
      out.write("\t  <input type=\"checkbox\" name=\"memHobby\" id=\"inter39\"value=\"기타\">\r\n");
      out.write("\t  <label for=\"inter39\">기타</label>\r\n");
      out.write("  </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\t<tr align=\"center\">\r\n");
      out.write("\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t<div class=\"btn_area\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"가입\" />\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"취소\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script charset=\"UTF-8\" type=\"text/javascript\"\r\n");
      out.write("   src=\"http://t1.daumcdn.net/cssjs/postcode/1522037570977/180326.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("   //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("   function sample4_execDaumPostcode() {\r\n");
      out.write("      new daum.Postcode(\r\n");
      out.write("            {\r\n");
      out.write("               oncomplete : function(data) {\r\n");
      out.write("                  // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                  // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                  // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                  var fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                  var extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                  // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                  // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                  if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                     extraRoadAddr += data.bname;\r\n");
      out.write("                  }\r\n");
      out.write("                  // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                  if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                     extraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("                           + data.buildingName : data.buildingName);\r\n");
      out.write("                  }\r\n");
      out.write("                  // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                  if (extraRoadAddr !== '') {\r\n");
      out.write("                     extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                  }\r\n");
      out.write("                  // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("                  if (fullRoadAddr !== '') {\r\n");
      out.write("                     fullRoadAddr += extraRoadAddr;\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("                  // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                  document.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                  document.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("                  document.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("                  // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                  if (data.autoRoadAddress) {\r\n");
      out.write("                     //예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("                     var expRoadAddr = data.autoRoadAddress\r\n");
      out.write("                           + extraRoadAddr;\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("                           + expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                  } else if (data.autoJibunAddress) {\r\n");
      out.write("                     var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("                           + expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                  } else {\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '';\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            }).open();\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2018. <strong>영중문고</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t\t<p>주소 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 2F, 3F</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
