/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-09 00:15:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import book.model.vo.Book;

public final class bestSeller_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("book.model.vo.Book");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	List<Book> bestSellerList = (List<Book>)request.getAttribute("bestSellerList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8\">\r\n");
      out.write("<title>BestSeller</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t*{\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tul,li{\r\n");
      out.write("\t\tlist-style:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\tbackground: gray;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide ul{\r\n");
      out.write("\t\twidth: 400%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\ttransition: 1s;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide ul:after{\r\n");
      out.write("\t\tcontent:\"\";\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\tclear:both;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide li{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth:25%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide li:nth-child(1){\r\n");
      out.write("\t\tbackground:#faa;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide li:nth-child(2){\r\n");
      out.write("\t\tbackground:#ffa;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide li:nth-child(3){\r\n");
      out.write("\t\tbackground:#faF;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide li:nth-child(4){\r\n");
      out.write("\t\tbackground:#aaf;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide input{\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide label{\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\tvertical-align:middle;\r\n");
      out.write("\t\twidth:10px;\r\n");
      out.write("\t\theight:10px;\r\n");
      out.write("\t\tborder:2px solid #666;\r\n");
      out.write("\t\tbackground:#fff;\r\n");
      out.write("\t\ttransition:0.3s;\r\n");
      out.write("\t\tborder-radius:50%;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#slide .page{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tbottom:10px;\r\n");
      out.write("\t\tleft:0;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#page1:checked~ul{\r\n");
      out.write("\t\tmargin-left:0%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#page2:checked~ul{\r\n");
      out.write("\t\tmargin-left:-100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#page3:checked~ul{\r\n");
      out.write("\t\tmargin-left:-200%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#page4:checked~ul{\r\n");
      out.write("\t\tmargin-left:-300%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#page1:checked~.page>label:nth-child(1){\r\n");
      out.write("\t\tbackground:#666;\r\n");
      out.write("\t}\r\n");
      out.write("\t#page2:checked~.page>label:nth-child(2){\r\n");
      out.write("\t\tbackground:#666;\r\n");
      out.write("\t}\r\n");
      out.write("\t#page3:checked~.page>label:nth-child(3){\r\n");
      out.write("\t\tbackground:#666;\r\n");
      out.write("\t}\r\n");
      out.write("\t#page4:checked~.page>label:nth-child(4){\r\n");
      out.write("\t\tbackground:#666;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tli>div{\r\n");
      out.write("\t\twidth: 160px;\r\n");
      out.write("\t\theight: 180px;\r\n");
      out.write("\t\tborder: 1px solid gray;\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t\tmargin-left: 85px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\tli>div:hover{\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"slide\">\r\n");
      out.write("\t\t<input type=\"radio\" name=\"page\" id=\"page1\" checked>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"page\" id=\"page2\">\r\n");
      out.write("\t\t<input type=\"radio\" name=\"page\" id=\"page3\">\r\n");
      out.write("\t\t<input type=\"radio\" name=\"page\" id=\"page4\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t");
 if( bestSellerList != null ){ 
					 for( int i = 0; i < bestSellerList.size(); i++ ){
      out.write("\r\n");
      out.write("\t\t\t\t\t \t");
 if( i%5 == 0) {
      out.write("\r\n");
      out.write("\t\t\t\t\t \t\t<li>\r\n");
      out.write("\t\t\t\t\t \t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t \t\t<div>\r\n");
      out.write("\t\t\t\t\t \t\t\t");
      out.print(bestSellerList.get(i).getBookNo() );
      out.write(" <br />\r\n");
      out.write("\t\t\t\t\t \t\t\t");
      out.print(bestSellerList.get(i).getAuthorName() );
      out.write(" <br />\r\n");
      out.write("\t\t\t\t\t \t\t\t");
      out.print(bestSellerList.get(i).getBookTitle() );
      out.write(" <br />\r\n");
      out.write("\t\t\t\t\t \t\t\t");
      out.print(bestSellerList.get(i).getBookPublisher() );
      out.write(" <br />\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t\t</div>\t\t\t\t\t \t\t\r\n");
      out.write("\t\t\t\t\t \t");
 if( i%5 == 4 ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t \t\t</li>\r\n");
      out.write("\t\t\t\t\t");
 	 }
					}
				}
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p class=\"page\">\r\n");
      out.write("\t\t\t<label for=\"page1\"></label>\r\n");
      out.write("\t\t\t<label for=\"page2\"></label>\r\n");
      out.write("\t\t\t<label for=\"page3\"></label>\r\n");
      out.write("\t\t\t<label for=\"page4\"></label>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
