/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-16 08:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.buy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.*;

public final class buy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1526448290425L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1525827172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("member.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
	//System.out.println(memberLoggedIn);
	
	//클라이언트가 보낸 쿠키처리(쿠키관련)
	Cookie[] cookies = request.getCookies();
	boolean saveId = false;
	String userIdSaved = "";
	
	//최초접속시 cookie는 null임.
	if(cookies != null){
	//	System.out.println("------------------------------------");
	//	System.out.println("브라우져가 전송한 쿠키목록");
	//	System.out.println("------------------------------------");
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
	//		System.out.println(key+" : "+value);
			//아이디저장 쿠키검사
			if("saveId".equals(key)){
				saveId = true;
				userIdSaved = value;
			}
		}
	//	System.out.println("------------------------------------");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gugi\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<title>Book</title>\r\n");
      out.write("<script>\r\n");
      out.write("//메뉴상단에 고정하기.(스크롤 내려도)\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tvar jbOffset = $( '.fixed-search1' ).offset();\r\n");
      out.write("\t$( '.fixed-search1' ).removeClass( 'jbFixed').css(\"display\",\"none\");\r\n");
      out.write("\t$( window ).scroll( function() {\r\n");
      out.write("\t\tif ( $( document ).scrollTop() > jbOffset.top ) {\r\n");
      out.write("\t\t\t$( '.fixed-search1' ).addClass( 'jbFixed' ).css(\"display\",\"inline\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t$( '.fixed-search1' ).removeClass( 'jbFixed').css(\"display\",\"none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("function fn_loginValidate(){\r\n");
      out.write("\t//아이디 검사\r\n");
      out.write("\tif($(\"#userId1\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#userId1\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t//패스워드 검사\r\n");
      out.write("\tif($(\"#password1\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#password1\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar cnt = 0;\r\n");
      out.write("\t$(\"#user1\").click(function(){\r\n");
      out.write("\t\tcnt++;\r\n");
      out.write("\t\tif(cnt%2==1){\r\n");
      out.write("\t\t\t$(\"#bubble1\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$(\"#bubble1\").css(\"display\",\"none\");\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("$(function(){\r\n");
      out.write("\t   $(\"#basket1\").click(function(){      \r\n");
      out.write("\t      ");
if( memberLoggedIn != null ) {
      out.write("\r\n");
      out.write("\t         var memberNo = ");
      out.print(memberLoggedIn.getMember_no());
      out.write(";\r\n");
      out.write("\t      ");
}
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t      location.href=\"");
      out.print(request.getContextPath());
      out.write("/basket/basketServlet?memberNo=\" + memberNo;\r\n");
      out.write("\t   });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container1\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"title1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.png\" alt=\"logo\" id=\"img-title1\"></a></div>\r\n");
      out.write("\t\t\t<!-- 검색바 -->\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/search/searchBook\" onsubmit=\"return fn_searchBook_byteCheck();\">\r\n");
      out.write("\t\t\t<div id=\"search-container1\">\r\n");
      out.write("\t\t\t<select name=\"searchType\" id =\"searchType1_1\">\r\n");
      out.write("\t\t\t\t<option value=\"all\" class=\"all-search\">통합검색</option>\r\n");
      out.write("\t\t\t\t<option value=\"title\" class=\"title-search\">책제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"writer\" class=\"writer-search\">저자명</option>\r\n");
      out.write("\t\t\t\t<option value=\"publisher\" class=\"publisher-search\">출판사명</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"searchBook\" id=\"search-book1_1\" placeholder=\"검색명을 입력하세요.\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"search1_1\" value=\"검색\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tfunction fn_searchBook_byteCheck() {\r\n");
      out.write("\t\t\tif($(\"#search-book1_1\").val().trim() == 0) {\r\n");
      out.write("\t\t\t\talert(\"검색어를 입력하세요\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- 로그인 시작 -->\r\n");
      out.write("\t\t<div class=\"login-container1\">\r\n");
      out.write("\t\t");
 if(memberLoggedIn ==null){
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" id=\"loginFrm1\" method=\"post\" onsubmit=\"return fn_loginValidate();\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"userId1\" placeholder=\"아이디\" value=\"");
      out.print(saveId?userIdSaved:"");
      out.write("\"/> </td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password1\" placeholder=\"비밀번호\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"로그인\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId1\"");
      out.print(saveId?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label id=\"saveId1\" for=\"saveId\">아이디저장</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"join1\" value=\"회원가입\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/chooseEnroll'\"/>     \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"logged-container1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"logged1\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"user1\" alt=\"user.png\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/user.png\">\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<span id=\"logged-name1\">");
      out.print(memberLoggedIn.getMember_name() );
      out.write("님</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"bubble1\" style=\"position:relative; dispaly:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"mpage1\" type=\"button\" value=\"마이페이지\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myPage';\"/>\r\n");
      out.write("\t\t\t\t\t\t<!-- ?member_id= ");
      out.print(memberLoggedIn.getMember_id());
      out.write(" -->\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<input id=\"basket1\"type=\"button\" value=\"장바구니\" />\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<input id=\"log-out1\" type=\"button\" value=\"로그아웃\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 로그인 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 메인메뉴시작 -->\r\n");
      out.write("\t\t<nav class=\"fix-nav1\">\r\n");
      out.write("\t\t\t<ul class=\"main-nav1\">\r\n");
      out.write("\t           <li class=\"book-list\"><a href=\"#\">도서</a></li>\r\n");
      out.write("\t           <li id=\"jiseojae\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/recommend/RecommenListServlet\">지서재</a></li>\r\n");
      out.write("\t           <li id=\"used-book\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/oldboard/OldBoardServlet\">중고장터</a></li>\r\n");
      out.write("\t           <li id=\"notice\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t           ");
      out.write("\r\n");
      out.write("\t           ");
if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMember_id())){ 
      out.write("\r\n");
      out.write("\t           <li id=\"ad-member3\"><a href=\"#\">회원관리</a></li>\r\n");
      out.write("\t            <li id=\"ad-book3\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/book/bookListView\">도서관리</a></li>\r\n");
      out.write("\t           ");
} 
      out.write("\r\n");
      out.write("         \t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t<!-- 상단에 고정될 검색창  -->\r\n");
      out.write("\t\t<div id=\"fixed-search-container1\" class=\"fixed-search1\">\r\n");
      out.write("\t\t<img id = \"slogo1\"src=\"");
      out.print(request.getContextPath());
      out.write("/images/small-logo.png\" alt=\"logo\" height=\"40\" width=\"70\"  style=\"vertical-align: middle\">\r\n");
      out.write("\t\t\t<select name=\"searchType1\" id =\"searchType2_1\" style=\"vertical-align: middle\">\r\n");
      out.write("\t\t\t\t<option value=\"search-all1\" >통합검색</option>\r\n");
      out.write("\t\t\t\t<option value=\"title1\" >책제목</option>\r\n");
      out.write("\t\t\t\t<option value=\"writer1\">저자명</option>\r\n");
      out.write("\t\t\t\t<option value=\"publisher1\">출판사명</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"search-book2_1\" placeholder=\"검색명을 입력하세요.\" style=\"vertical-align: middle\"/>\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"search2_1\" value=\"검색\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<section id=\"content1\">\r\n");
      out.write('\r');
      out.write('\n');

	String bookNo = request.getParameter("bookNo");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("   user-select: none;    \r\n");
      out.write("}\r\n");
      out.write("span.index2 {\r\n");
      out.write("   color: #4374D9;\r\n");
      out.write("   font-size: 25px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.content2 {\r\n");
      out.write("   font-size: 25px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.order2 {\r\n");
      out.write("   border: 1px solid;\r\n");
      out.write("   border-collapse: collapse;\r\n");
      out.write("   margin: 10px;\r\n");
      out.write("   width: 940px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td.float_right2 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.book2 {\r\n");
      out.write("   width: 100px;\r\n");
      out.write("   height: 120px;\r\n");
      out.write("   border: 1px solid;\r\n");
      out.write("   margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.order2 td {\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td#bookname2 {\r\n");
      out.write("   text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.price2 {\r\n");
      out.write("   font-size: 25px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.won2 {\r\n");
      out.write("   font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.total2 {\r\n");
      out.write("   color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#order_list2 th {\r\n");
      out.write("   background: #EAEAEA;\r\n");
      out.write("   border-bottom: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#sum2 {\r\n");
      out.write("   border-color: #899bdb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#sum2 th {\r\n");
      out.write("   background: #dee6fd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#sum2 td {\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.price2 {\r\n");
      out.write("   border: 0px;\r\n");
      out.write("   width: 30px;\r\n");
      out.write("   height: 30px;\r\n");
      out.write("   float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=button].btn2 {\r\n");
      out.write("   margin: 5px;\r\n");
      out.write("   background: white;\r\n");
      out.write("   border-color: #899bdb;\r\n");
      out.write("   padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=button].delivery2 {\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=button].btn2:hover, input[type=button].btn2:focus {\r\n");
      out.write("   background: #899bdb;\r\n");
      out.write("   color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#info2 {\r\n");
      out.write("   border: 0px;\r\n");
      out.write("   width: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#info-container2 td {\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th.info-container2 {\r\n");
      out.write("   background: #EAEAEA;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#info2 th {\r\n");
      out.write("   font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#info2 td {\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sample4_jibunAddress {\r\n");
      out.write("   margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#delivery_notice2, div#card_info2 {\r\n");
      out.write("   z-index: 1;\r\n");
      out.write("   visibility: hidden;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#popup2 {\r\n");
      out.write("   width: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#payment2 th, table#payment_info2 th{\r\n");
      out.write("   width: 140px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#payment2 {\r\n");
      out.write("   background: #fbfbfb;\r\n");
      out.write("   border-bottom: 1px dashed gray;\r\n");
      out.write("   margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#payment_info2 {\r\n");
      out.write("   margin-top: 0px;\r\n");
      out.write("   border-top: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr.hr_dotted2 {\r\n");
      out.write("   border-style: dashed;\r\n");
      out.write("   border-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.span_blue2 {\r\n");
      out.write("   color: #3a60df;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script charset=\"UTF-8\" type=\"text/javascript\"\r\n");
      out.write("   src=\"http://t1.daumcdn.net/cssjs/postcode/1522037570977/180326.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("   //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("   function sample4_execDaumPostcode() {\r\n");
      out.write("      new daum.Postcode(\r\n");
      out.write("            {\r\n");
      out.write("               oncomplete : function(data) {\r\n");
      out.write("                  // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                  // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                  // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                  var fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                  var extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                  // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                  // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                  if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                     extraRoadAddr += data.bname;\r\n");
      out.write("                  }\r\n");
      out.write("                  // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                  if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                     extraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("                           + data.buildingName : data.buildingName);\r\n");
      out.write("                  }\r\n");
      out.write("                  // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                  if (extraRoadAddr !== '') {\r\n");
      out.write("                     extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                  }\r\n");
      out.write("                  // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("                  if (fullRoadAddr !== '') {\r\n");
      out.write("                     fullRoadAddr += extraRoadAddr;\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("                  // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                  document.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                  document.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("                  document.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("                  // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                  if (data.autoRoadAddress) {\r\n");
      out.write("                     //예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("                     var expRoadAddr = data.autoRoadAddress\r\n");
      out.write("                           + extraRoadAddr;\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("                           + expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                  } else if (data.autoJibunAddress) {\r\n");
      out.write("                     var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("                           + expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                  } else {\r\n");
      out.write("                     document.getElementById('guide').innerHTML = '';\r\n");
      out.write("                  }\r\n");
      out.write("               }\r\n");
      out.write("            }).open();\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("   <span class=\"index2\">01</span>\r\n");
      out.write("   <span class=\"content2\">주문상품 목록</span>\r\n");
      out.write("   <table id=\"order_list2\" class=\"order2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th colspan=\"2\">상품정보</th>\r\n");
      out.write("         <th>판매가</th>\r\n");
      out.write("         <th>수량</th>\r\n");
      out.write("         <th>합계</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td><img class=\"book2\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/book.jpg\" alt=\"\" /></td>\r\n");
      out.write("         <td id=\"bookname2\">[도서]우리집에 곰이 이사왔다</td>\r\n");
      out.write("         <td class=\"float_right2\">9,000원</td>\r\n");
      out.write("         <td class=\"float_right2\">1</td>\r\n");
      out.write("         <td class=\"float_right2\">9,000원</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   상품 변경을 원하시면\r\n");
      out.write("   <input class=\"btn2\" type=\"button\" value=\"장바구니가기\" />\r\n");
      out.write("   <table id=\"sum2\" class=\"order2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>상품금액</th>\r\n");
      out.write("         <th>배송비</th>\r\n");
      out.write("         <th>결제 예정금액</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td>\r\n");
      out.write("            <span class=\"price2\">9,000</span><span class=\"won\">원</span> \r\n");
      out.write("            <img class=\"price2\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/plus.png\" alt=\"\" />\r\n");
      out.write("         </td>\r\n");
      out.write("\r\n");
      out.write("         <td>\r\n");
      out.write("            <span class=\"price2\">2,500</span><span class=\"won\">원</span> \r\n");
      out.write("            <img class=\"price2\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/equal.png\" alt=\"\" />\r\n");
      out.write("         </td>\r\n");
      out.write("         <td>\r\n");
      out.write("            <span class=\"price2 total2\">11,500</span><span class=\"won2 total2\">원</span>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   <br />\r\n");
      out.write("\r\n");
      out.write("   <span class=\"index2\">02</span>\r\n");
      out.write("   <span class=\"content2\">배송지</span> <span id=\"notice\">&nbsp;&nbsp;배송 유의사항</span> <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/question.png\" alt=\"question\" onMouseOver=\"showPreview();\" onMouseOut=\"hidePreview(); return true;\"/>\r\n");
      out.write("   <script>\r\n");
      out.write("   function showPreview() {\r\n");
      out.write("      var content = \"<div><h2>출고예정일이란?</h2><ul>\"\r\n");
      out.write("            + \"<li>주문상품의 결제(입금)가 확인 된 날 기준으로 상품을 준비/포장하여 <br /><strong style='color:blue;'>물류센터에서 택배사로 전달하는 예상 일정</strong> 입니다.</li>\"\r\n");
      out.write("            + \"<li>무통장 입금시, 입금 완료 시간 기준으로 결제확인이 되어 출고 예정일이 변경 될 수 있습니다.</li>\" \r\n");
      out.write("            + \"<li>상품 출고일이 다른 상품을 함께 주문 할 경우, 배송일정이 가장 늦은 상품 기준으로 노출 됩니다.</li></ul>\"\r\n");
      out.write("            + \"<h2>배송일정</h2>\" \r\n");
      out.write("            + \"<ul>\"\r\n");
      out.write("            + \"<li><strong style='color:blue;>배송일정은 “출고예정일 + 약 1~2일(택배사 배송일)”입니다.</strong><br>\"\r\n");
      out.write("            + \"<strong style='color:blue;>(연휴 및 토,일, 공휴일을 제외한 근무일 기준)</strong></li>\"\r\n");
      out.write("            + \"<li>날씨나 택배사의 사정에 따라 배송이 지연될 수 있습니다.</li>\"\r\n");
      out.write("            + \"<li>출고예정일이 5일 이후 이상인 상품의 경우(결제일로부터 7일동안 미입고), 출판사/유통사 사정으로 품/절판 되어 구입이 어려울 수 있습니다. 이 경우 SMS,메일로 알려드립니다.</li></ul>\";\r\n");
      out.write("      var text; \r\n");
      out.write("        text = '<table id=\"popup2\" cellpadding=\"5\" bgcolor=\"#ffffff\" style=\"font-size:9pt; filter:alpha(opacity=90); border-width:1; border-color:#3291BD; border-style:solid;\">'; \r\n");
      out.write("        text += '<tr><td>' + content + '</td></tr></table>'; \r\n");
      out.write("        document.getElementById('delivery_notice2').innerHTML = text; \r\n");
      out.write("        document.getElementById('delivery_notice2').style.visibility = 'visible'; \r\n");
      out.write("   }\r\n");
      out.write("   function hidePreview() {\r\n");
      out.write("      document.getElementById('delivery_notice2').innerHTML = ''; \r\n");
      out.write("       document.getElementById('delivery_notice2').style.visibility = 'hidden'; \r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("   <div id=\"delivery_notice2\"></div>\r\n");
      out.write("   <table id=\"info-container2\" class=\"order2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th class=\"info-container2\">주문자 정보</th>\r\n");
      out.write("         \r\n");
      out.write("         <td>\r\n");
      out.write("         ");
 if(memberLoggedIn != null) { 
      out.write(" \r\n");
      out.write("         \t");
      out.print(memberLoggedIn.getMember_name());
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(memberLoggedIn.getMember_email() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(memberLoggedIn.getMember_phone());
      out.write("\r\n");
      out.write("         ");
 } 
      out.write("\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <!--       <tr>\r\n");
      out.write("         <th>배송방법</th>\r\n");
      out.write("         <td>\r\n");
      out.write("            <input type=\"radio\" name=\"delivery\" id=\"local\" value=\"local\"/>\r\n");
      out.write("            <label for=\"local\">국내배송</label>\r\n");
      out.write("            <input type=\"radio\" name=\"delivery\" id=\"convenience\" value=\"convenience\"/>\r\n");
      out.write("            <label for=\"convenience\">편의점배송</label>\r\n");
      out.write("            <input type=\"radio\" name=\"delivery\" id=\"abroad\" value=\"abroad\"/>\r\n");
      out.write("            <label for=\"abroad\">해외배송</label>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr> -->\r\n");
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th class=\"info-container2\">배송지 정보</th>\r\n");
      out.write("         <td>\r\n");
      out.write("            <!-- <input class=\"delivery\" type=\"button\" value=\"최근 배송지\" /> --> \r\n");
      out.write("            <input class=\"btn2 delivery2\" type=\"button\" value=\"회원정보 동일\" /> \r\n");
      out.write("            <input class=\"btn2 delivery2\" type=\"button\" value=\"주소록\" /> \r\n");
      out.write("            <input class=\"btn2 delivery2\" type=\"button\" value=\"신규입력\" /> <br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <table id=\"info2\">\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th>받으시는 분</th>\r\n");
      out.write("                  <td colspan=\"3\">\r\n");
      out.write("                     <input type=\"text\" title=\"받으시는분\" style=\"width: 100px;\" onkeyup=\"checkBytes(this, '10');\">\r\n");
      out.write("                     <span>(10자 내외 입력)</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th>휴대폰 번호</th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <select id=\"phone_num1\" title=\"휴대폰 앞자리\" name=\"phone_num1\">\r\n");
      out.write("                           <option value=\"010\">010</option>\r\n");
      out.write("                           <option value=\"011\">011</option>\r\n");
      out.write("                           <option value=\"016\">016</option>\r\n");
      out.write("                           <option value=\"017\">017</option>\r\n");
      out.write("                           <option value=\"018\">018</option>\r\n");
      out.write("                           <option value=\"019\">019</option>\r\n");
      out.write("                     </select> - \r\n");
      out.write("                     <input id=\"phone_num2\" type=\"text\" title=\"중간자리\" style=\"width: 40px;\" phone_num2\" maxlength=\"4\"> - \r\n");
      out.write("                     <input id=\"phone_num3\" type=\"text\" title=\"뒷자리\" style=\"width: 40px;\" phone_num3\" maxlength=\"4\">\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th>배송 주소</th>\r\n");
      out.write("                  <td colspan=\"3\">\r\n");
      out.write("                     <input type=\"text\" id=\"sample4_postcode\" placeholder=\"우편번호\"> \r\n");
      out.write("                     <input type=\"button\" class=\"btn2\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("                     <input type=\"text\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\" size=\"35px\"> <br /> \r\n");
      out.write("                     <input type=\"text\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\" size=\"35px\">\r\n");
      out.write("                     <span id=\"guide\" style=\"color: #999\"></span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th class=\"info-container2\">배송 메세지</th>\r\n");
      out.write("         <td>\r\n");
      out.write("            <input type=\"text\" name=\"msg\" list=\"msg\" size=\"40px\" placeholder=\"직접입력\"> \r\n");
      out.write("            <!-- datalist id값과 위에 input의 list 속성 값이 일치해야 함. -->\r\n");
      out.write("            <datalist id=\"msg\">\r\n");
      out.write("            <option value=\"부재시 경비실에 맡겨주세요.\">\r\n");
      out.write("            <option value=\"부재시 휴대폰으로 연락바랍니다.\">\r\n");
      out.write("            <option value=\"집 앞에 놓아주세요.\">\r\n");
      out.write("            <option value=\"택배함에 넣어주세요.\">\r\n");
      out.write("            </datalist>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   <br />\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <span class=\"index2\">03</span>\r\n");
      out.write("   <span class=\"content2\">결제정보</span>\r\n");
      out.write("   <div id=\"card_info2\"></div>\r\n");
      out.write("   <table id=\"payment2\" class=\"order2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>신용카드</th>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"card\" checked/><label for=\"card\">신용카드(일반)</label></td>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"card2\" /><label for=\"card2\">제휴신용카드</label></td>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"card3\" /><label for=\"card3\">해외발급신용카드</label></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>간편결제</th>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"kakao\" /><label for=\"kakao\">카카오페이</label></td>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"payco\" /><label for=\"payco\">PAYCO</label></td>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"samsung\" /><label for=\"samsung\">삼성페이</label></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>현금결제</th>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"account\" /><label for=\"account\">실시간 계좌이체</label></td>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"remit\" /><label for=\"remit\">온라인(무통장) 송금</label></td>\r\n");
      out.write("         <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>기타결제</th>\r\n");
      out.write("         <td><input type=\"radio\" name=\"pay\" id=\"phone\" /><label for=\"phone\">휴대폰 결제</label></td>\r\n");
      out.write("         <td></td>\r\n");
      out.write("         <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      \r\n");
      out.write("      <table id=\"payment_info2\" class=\"order2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <div id=\"payment-container2\">\r\n");
      out.write("            <th>신용카드</th>\r\n");
      out.write("            <td>\r\n");
      out.write("            <div id=\"card2\">\r\n");
      out.write("               <select id=\"selectCard1\" name=\"default_card\" title=\"카드선택\">\r\n");
      out.write("                  <option value=\"\">결제하실 카드를 선택해주세요</option>\r\n");
      out.write("                  <option value=\"SH\">신한카드(구LG)</option>\r\n");
      out.write("                  <option value=\"KB\">KB국민카드</option>\r\n");
      out.write("                  <option value=\"BC\">BC카드</option>\r\n");
      out.write("                  <option value=\"HD\">현대카드</option>\r\n");
      out.write("                  <option value=\"LT\">롯데카드</option>\r\n");
      out.write("                  <option value=\"WH\">외환카드</option>\r\n");
      out.write("                  <option value=\"SS\">삼성카드</option>\r\n");
      out.write("                  <option value=\"UR\">우리카드</option>\r\n");
      out.write("                  <option value=\"HN\">하나카드</option>\r\n");
      out.write("                  <option value=\"CT\">씨티카드</option>\r\n");
      out.write("                  <option value=\"JC\">저축은행카드</option>\r\n");
      out.write("                  <option value=\"UC\">우체국카드</option>\r\n");
      out.write("                  <option value=\"SM\">MG새마을체크카드</option>\r\n");
      out.write("                  <option value=\"SUH\">수협카드</option>\r\n");
      out.write("                  <option value=\"JB\">전북JB카드</option>\r\n");
      out.write("                  <option value=\"KJ\">광주은행카드</option>\r\n");
      out.write("                  <option value=\"NH\">NH카드</option>\r\n");
      out.write("                  <option value=\"SIH\">신협카드</option>\r\n");
      out.write("                  <option value=\"JJ\">제주카드</option>\r\n");
      out.write("                  <option value=\"SU\">KDB산업은행카드</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </div>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>카드구분</th>\r\n");
      out.write("         <td>\r\n");
      out.write("            <input type=\"radio\" name=\"card\" id=\"personal_card2\" /><label for=\"personal_card2\">개인카드</label>\r\n");
      out.write("            <input type=\"radio\" name=\"card\" id=\"business_card2\" /><label for=\"business_card2\">법인카드</label>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>결제안내</th>\r\n");
      out.write("         <td>\r\n");
      out.write("            <input class=\"btn2\" type=\"button\" value=\"결제오류안내\" onMouseOver=\"fn_popup();\" onMouseOut=\"fn_hide(); return true;\"/>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   function fn_popup() {\r\n");
      out.write("      var content = \"<span class='span_blue2'>■ 주문/결제페이지에서 [결제하기] 누른 후 주문중으로 계속 표시되고 주문완료가 되지 않을 경우</span><br />\"\r\n");
      out.write("               + \"고객님의 카드번호 혹은 유효기간 입력 등이 잘못되거나 카드에 문제가 발생할 경우 결제 승인이 정상적으로 되지 않을 수 있습니다.<br /> 각 카드 발급사에 문의 부탁드립니다. \"\r\n");
      out.write("               + \"<hr class='hr_dotted2'/>\"\r\n");
      out.write("               + \"<span class='span_blue2'>■ '보안된 컨텐츠만 표시됩니다'라는 보안경고가 계속 뜨는 경우</span><br /> \"\r\n");
      out.write("               + \"암호화할 필요가 없는 이미지나 사진 같은 요소가 포함된 경우 보안경고가 생성될 수 있습니다. 아래와 같이 설정을 변경하세요. <br /><br /> \"\r\n");
      out.write("               + \"1. IE 메뉴에서 [도구] -> [인터넷옵션] -> [보안]탭 <br />2. [도구] -> [인터넷옵션] -> [보안] 탭 -> [사용자지정수준 ] <br />\"\r\n");
      out.write("               + \"3. 하단 [기타] 메뉴에서 [혼합된 콘텐츠 표시]라는 항목을 '사용'이나 '사용안함'으로 설정\";\r\n");
      out.write("      var text; \r\n");
      out.write("        text = '<table id=\"popup2\" cellpadding=\"5\" bgcolor=\"#ffffff\" style=\"font-size:9pt; filter:alpha(opacity=90); border-width:1; border-color:#3291BD; border-style:solid;\">'; \r\n");
      out.write("        text += '<tr><td>' + content + '</td></tr></table>'; \r\n");
      out.write("        document.getElementById('card_info2').innerHTML = text; \r\n");
      out.write("        document.getElementById('card_info2').style.visibility = 'visible'; \r\n");
      out.write("   }\r\n");
      out.write("   function fn_hide() {\r\n");
      out.write("      document.getElementById('card_info2').innerHTML = ''; \r\n");
      out.write("       document.getElementById('card_info2').style.visibility = 'hidden'; \r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2018. <strong>영중문고</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t\t<p>주소 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 2F, 3F</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
